[package]
name = "AdventOfCode"
version = "0.1.0"
authors = ["Vanglant <mikay264@hotmail.com>"]
edition = "2018"

[dependencies]

[[bin]]
name = "day1"
path = "src/day1.rs"

[[bin]]
name = "day1b"
path = "src/day1plus.rs"

[[bin]]
name = "day2"
path = "src/day2.rs"